server:
  port: 8082
  servlet:
    context-path: /crud-alunos
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      show-actuator: 'true'

  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:testdb
    username:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
