spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      show-actuator: 'true'

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}S
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update


